version: '3'

services:
  the-movie-database:
    container_name: the-movie-database-container
    build: .
    image: the-movie-database:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
